### ISSUE TITLE
Why binary IDs?

### ISSUE THREAD

**Issue by txgruppi** [openaccounting/oa-server#3]
I'm curious to know why did you choose to use binary IDs?

From the system's perspective it makes no difference the data type used but when checking the database _as a human_ it is not very friendly.

Why not store the a `CHAR(32)`?

**Comment by pnagurny** [comment]
Originally the id's were just BIGINT AUTO_INCREMENT. I switched to using GUID's. In my reading online of GUID's and MySQL I noted that a lot of people were using BINARY(16) instead of CHAR(32) to improve performance. For indexes that are held in memory, the server only needs half as much memory to have the same amount of objects.

The good news is you can make MySQL much more human friendly by using the --binary-as-hex option. When you are doing manual queries it will show you the hex string version. You can use the HEX() and UNHEX() functions to help you do WHERE clauses, etc.

Hope this answers your question!

**Comment by txgruppi** [comment]
Thanks @pnagurny.
